name: dl-challenge
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy<=1.16.4
  - scipy
  - pandas
  - matplotlib
  - pip
  - scikit-image
  - scikit-learn
  - jupyterlab
  - tqdm>=4.36
  - pip:
      - onnxruntime
      - torch
      - torchvision
      - torchaudio
      - --index-url https://download.pytorch.org/whl/cu126
